/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author johannesr
 */
public class RegisterNewUser extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public RegisterNewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new java.awt.Label();
        StudentNumField = new javax.swing.JTextField();
        IDNumField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        GetFPButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setAlignment(java.awt.Label.CENTER);
        Exit.setBackground(new java.awt.Color(221, 131, 131));
        Exit.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setName(""); // NOI18N
        Exit.setText("Back");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 30));

        StudentNumField.setText("Enter Your Student Number");
        StudentNumField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StudentNumFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                StudentNumFieldFocusLost(evt);
            }
        });
        StudentNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNumFieldActionPerformed(evt);
            }
        });
        getContentPane().add(StudentNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 30));

        IDNumField.setText("Enter ID Number");
        IDNumField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDNumFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDNumFieldFocusLost(evt);
            }
        });
        IDNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNumFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IDNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 30));

        NameField.setText("Enter Your Name");
        NameField.setToolTipText("tftfytfytfy");
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NameFieldMouseEntered(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 30));

        GetFPButton.setText("Get Fingerprints");
        GetFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetFPButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GetFPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 40));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setForeground(new java.awt.Color(238, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture3.png"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
               dispose();
      new Main().setVisible(true);
    }//GEN-LAST:event_ExitMouseClicked

    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusGained
        // TODO add your handling code here:
        if("Enter Your Name".equals(NameField.getText())){
            NameField.setText("");
        }
        
    }//GEN-LAST:event_NameFieldFocusGained

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        // TODO add your handling code here:
       if("".equals(NameField.getText())){
            NameField.setText("Enter Your Name");
        }
    }//GEN-LAST:event_NameFieldFocusLost

    private void NameFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldMouseEntered

    private void IDNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNumFieldActionPerformed

    private void IDNumFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDNumFieldFocusGained
        // TODO add your handling code here:
        if("Enter ID Number".equals(IDNumField.getText())){
            IDNumField.setText("");
        }
    }//GEN-LAST:event_IDNumFieldFocusGained

    private void IDNumFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDNumFieldFocusLost
        // TODO add your handling code here:
                       if("".equals(IDNumField.getText())){
            IDNumField.setText("Enter ID Number");
        }
    }//GEN-LAST:event_IDNumFieldFocusLost

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void StudentNumFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StudentNumFieldFocusGained
        // TODO add your handling code here:
                if("Enter Your Student Number".equals(StudentNumField.getText())){
            StudentNumField.setText("");
        }
    }//GEN-LAST:event_StudentNumFieldFocusGained

    private void StudentNumFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StudentNumFieldFocusLost
        // TODO add your handling code here:
               if("".equals(StudentNumField.getText())){
            StudentNumField.setText("Enter Your Student Number");
        }
    }//GEN-LAST:event_StudentNumFieldFocusLost

    private void StudentNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNumFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StudentNumFieldActionPerformed

    private void GetFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetFPButtonActionPerformed
        // TODO add your handling code here:
        //NameField.getText();
        //IDNumField.getText();
        //StudentNumField.getText();
  try{  
  Class.forName("com.mysql.jdbc.Driver");  
  Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/attendancereg","fingerprintApp","fingerprintApp");  
 //here attendancereg is database name, fingerprintApp is username and password 
      
 String query= "INSERT INTO `attendancereg`.`students` (`StudentIDNo`, `StudentNumber`, `Nameandsurname`, `Fingerprint`) VALUES (?,?, ?, ?)";
            
      PreparedStatement preparedStmt = con.prepareStatement(query);
      preparedStmt.setString (1, IDNumField.getText());
      preparedStmt.setString (2, StudentNumField.getText());
      preparedStmt.setString   (3, NameField.getText());
      preparedStmt.setString(4, "son");

     preparedStmt.execute();
              
            con.close();  
        } 
        catch(Exception e){ 
            System.out.println(e);
        }
        
        
        

        
        
    }//GEN-LAST:event_GetFPButtonActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Exit;
    private javax.swing.JButton GetFPButton;
    private javax.swing.JTextField IDNumField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField StudentNumField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
